shadow_models:
  - name: "k neighbors classifier"
    params:
      n_neighbors: 18
      leaf_size: 40
      p: 2
      n_jobs: 1
target_property: pitch_angle_bin
pred_property: gearbox_temp_bin
shadow_model_ratios: [0.1, 0.8]
data_path: "/home/ujx4ab/ondemand/WindTurbine_KL_Divergence/Data/combined_data.csv"
test_ratio: 0.2