model_name: "random forest classifier"
model_params:
  n_estimators: 250
  max_depth: 40
target_property: pitch_angle_bin
pred_property: gearbox_temp_bin
shadow_model_ratios: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
data_path: "/home/ujx4ab/ondemand/WindTurbine_KL_Divergence/Data/combined_data.csv"
test_ratio: 0.2